[package]
name = "courier_ql"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
hyper = { version = "=1.0.0-rc.2", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1.0-rc.2"
bytes = "1"
futures = "0.3.26"
hyper-util = "0.0.0"
url = "2.4.1"

