courier.version = "0.1"

[simple.graphql]
url = "https://swapi-graphql.netlify.app/.netlify/functions/index"
query = '''
{
    allFilms {
        films {
        title
        }
    }
}'''
[simple.graphql.http1]
method = "POST"

[get.graphql]
url = "http://example.com/test"
query = '''{
    allFilms {
        films {
        title
        }
    }
}'''
[get.http]
method = "GET"

[query_string.graphql]
url = "https://swapi-graphql.netlify.app/.netlify/functions/index"
query = '''{
    allFilms {
        films {
        title
        }
    }
}'''
use_query_string = true
[query_string.graphql.http]
method = "GET"
headers = { Content-Type = { unset = true } }
