courier.version = "0.1"

[http_pause.http]
url = "https://example.com/"
pause.after.open.duration = "500ms"
pause.after.request_body.duration = "500ms"

[multi_pause.tls]
host = "example.com"
port = "443"
body = "GET / HTTP/1.0\r\n\r\n"
pause.after.open.duration = "500ms"
[[multi_pause.tls.pause.after.request_body]]
duration = "500ms"
[[multi_pause.tls.pause.after.request_body]]
offset_bytes = 50
duration = "500ms"
[multi_pause.tls.pause.after.response_headers]
match = "<< >>"
offset_bytes = 50
duration = "500ms"
