# Simple HTTPS GET
[a.http]
url = "https://example.com/test"

url = "https://example.com/test"
[b.http.headers]
Content-Type.cel = "application/{{ if a.http.response.json.foo else bar }}/{{ foo }}"

[c.http]
url = "https://example.com/test"
[c.http.pause] = [{after = "head", duration = "5ms"}, {}]
after_headers = "50ms"
after_handshake = "10ms"
after_done = "100ms"
[c.run]
while.cel = ""
for.cel = "def"
if = ""
