devil.version = 0

[[devil.defaults]]
selector = ["graphql", "graphqlh1c", "graphqlh1", "graphqlh2", "graphqlh2c", "graphqlh3"]
    [devil.defaults.http]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [devil.defaults.h1c]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [devil.defaults.h1]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [devil.defaults.h2c]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [devil.defaults.h2]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [devil.defaults.h3]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    body.cel = "current.graphql.plan.body.to_json()"
    headers.Content-Type = "application/json"
    headers.Content-Length.cel = "current.graphql.plan.body.to_json().len()"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"

[[devil.defaults]]
selector = ["h1c", "graphqlh1c"]
    [devil.defaults.tcp]
    host.cel = "current.h1c.plan.url.parse_url().host"
    port.cel = "current.h1c.plan.url.parse_url().port_or_default"

[[devil.defaults]]
selector = ["h1", "graphqlh1"]
    [devil.defaults.tls]
    host.cel = "current.h1.plan.url.parse_url().host"
    port.cel = "current.h1.plan.url.parse_url().port_or_default"

[[devil.defaults]]
selector = ["h2c", "graphqlh2c"]
    [devil.defaults.http2frames]
    host.cel = "current.h2c.plan.url.parse_url().host"
    port.cel = "current.h2c.plan.url.parse_url().port_or_default"
    [devil.defaults.tcp]
    host.cel = "current.http2frames.plan.host"
    port.cel = "current.http2frames.plan.port"

[[devil.defaults]]
selector = ["h2", "graphqlh2"]
    [devil.defaults.http2frames]
    host.cel = "current.h2.plan.url.parse_url().host"
    port.cel = "current.h2.plan.url.parse_url().port_or_default"
    [devil.defaults.tls]
    host.cel = "current.http2frames.plan.host"
    port.cel = "current.http2frames.plan.port"
    alpn = "h2"

[[devil.defaults]]
selector = ["tls", "h1", "h2", "graphqlh1", "graphqlh2"]
    [devil.defaults.tcp]
    host.cel = "current.tls.plan.host"
    port.cel = "current.tls.plan.port"

[[devil.defaults]]
selector = ["dtls"]
    [devil.defaults.udp]
    host.cel = "current.dtls.plan.host"
    port.cel = "current.dtls.plan.port"

[[devil.defaults]]
    http.method = "GET"
    http.add_content_length = "auto"
    h1c.method = "GET"
    h1c.add_content_length = "auto"
    h1c.version_string = "HTTP/1.1"
    h1.method = "GET"
    h1.add_content_length = "auto"
    h1.version_string = "HTTP/1.1"
    h2c.method = "GET"
    h2c.add_content_length = "auto"
    h2.method = "GET"
    h2.add_content_length = "auto"
    tcp.close.timeout = "30s"

