courier.version = 0

[[courier.defaults]]
selector = ["graphql", "graphqlh1c", "graphqlh1", "graphqlh2", "graphqlh2c", "graphqlh3"]
    [courier.defaults.http]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    [courier.defaults.h1c]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    [courier.defaults.h1]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    [courier.defaults.h2c]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    [courier.defaults.h2]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    [courier.defaults.h3]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"

[[courier.defaults]]
selector = ["h1c"]
    [courier.defaults.tcp]
    host.cel = "current.h1c.plan.url.parse_url().host"
    port.cel = "current.h1c.plan.url.parse_url().port_or_default"

[[courier.defaults]]
selector = ["h1"]
    [courier.defaults.tls]
    host.cel = "current.h1.plan.url.parse_url().host"
    port.cel = "current.h1.plan.url.parse_url().port_or_default"
    [courier.defaults.tcp]
    host.cel = "current.h1.plan.url.parse_url().host"
    port.cel = "current.h1.plan.url.parse_url().port_or_default"

[[courier.defaults]]
selector = ["h2c"]
    [courier.defaults.tcp]
    host.cel = "current.h2c.plan.url.parse_url().host"
    port.cel = "current.h2c.plan.url.parse_url().port_or_default"

[[courier.defaults]]
selector = ["h2"]
    [courier.defaults.tls]
    host.cel = "current.h2.plan.url.parse_url().host"
    port.cel = "current.h2.plan.url.parse_url().port_or_default"
    [courier.defaults.tcp]
    host.cel = "current.h2.plan.url.parse_url().host"
    port.cel = "current.h2.plan.url.parse_url().port_or_default"

[[courier.defaults]]
selector = ["tls"]
    [courier.defaults.tcp]
    host.cel = "current.tls.plan.host"
    port.cel = "current.tls.plan.port"

[[courier.defaults]]
selector = ["dtls"]
    [courier.defaults.udp]
    host.cel = "current.dtls.plan.host"
    port.cel = "current.dtls.plan.port"

[[courier.defaults]]
    http.method = "GET"
    h1c.method = "GET"
    h1c.version_string = "HTTP/1.1"
    h1.method = "GET"
    h1.version_string = "HTTP/1.1"
    h2c.method = "GET"
    h2.method = "GET"
